using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ChibiRuby.Serializer.SourceGenerator;

[Generator]
public class ChibiRubySerializerSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Extract a fully value-equatable model in the transform stage. This keeps the
        // pipeline free of Compilation/symbol/syntax references, so the incremental driver
        // can cache per type and skip generation when nothing relevant changed.
        var models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "ChibiRuby.Serializer.MRubyObjectAttribute",
                static (node, _) =>
                    node is ClassDeclarationSyntax or StructDeclarationSyntax or RecordDeclarationSyntax,
                static (context, cancellation) => MRubyObjectModel.Create(context, cancellation))
            .WithTrackingName("MRubyObjectModels");

        context.RegisterSourceOutput(models, static (productionContext, model) =>
        {
            foreach (var diagnostic in model.Diagnostics)
            {
                productionContext.ReportDiagnostic(diagnostic.ToDiagnostic());
            }

            if (model.HasError)
            {
                return;
            }

            var stringBuilder = new StringBuilder();
            Emit(model, stringBuilder);
            productionContext.AddSource($"{model.HintName}.g.cs", stringBuilder.ToString());
        });

        // Assembly-wide facts needed by the module initializer. Extracted into an equatable
        // model so the aggregate output below still caches when nothing relevant changed.
        var assemblyMeta = context.CompilationProvider
            .Select(static (compilation, cancellation) => AssemblyMeta.Create(compilation, cancellation))
            .WithTrackingName("ChibiRubyAssemblyMeta");

        // Aggregate output: one [ModuleInitializer] per assembly that eagerly registers every
        // generated formatter. This roots all registrations statically, so trimming, NativeAOT
        // and Unity's IL2CPP/linker need no runtime reflection (see issue #199).
        context.RegisterSourceOutput(models.Collect().Combine(assemblyMeta), static (productionContext, pair) =>
        {
            var (allModels, meta) = pair;
            foreach (var diagnostic in meta.Diagnostics)
            {
                productionContext.ReportDiagnostic(diagnostic.ToDiagnostic());
            }
            EmitModuleInitializer(allModels, meta, productionContext);
        });
    }

    static void EmitModuleInitializer(
        ImmutableArray<MRubyObjectModel> models,
        AssemblyMeta meta,
        SourceProductionContext context)
    {
        var typeInitializers = models
            .Where(x => x is { HasError: false, EmitInInitializer: true })
            .Select(x => x.FullTypeName)
            .Distinct()
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToArray();

        if (typeInitializers.Length <= 0 && meta.RootStatements.Count <= 0)
        {
            return;
        }

        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("""
// <auto-generated />
#nullable enable
""");
        if (!meta.HasModuleInitializerAttribute)
        {
            stringBuilder.AppendLine("""
namespace System.Runtime.CompilerServices
{
    // Polyfill for target frameworks (netstandard2.1 / Unity) that do not ship this attribute.
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, Inherited = false)]
    internal sealed class ModuleInitializerAttribute : global::System.Attribute
    {
    }
}

""");
        }
        stringBuilder.AppendLine("""
namespace ChibiRuby.Serializer.Generated
{
    /// <summary>
    /// Eagerly registers every generated mruby formatter in this assembly on assembly load.
    /// Registration is rooted statically here, so it survives trimming, NativeAOT and
    /// Unity's IL2CPP/linker without relying on reflection or runtime attribute instances.
    /// </summary>
    internal static class ChibiRubySerializerModuleInitializer
    {
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        [global::ChibiRuby.Serializer.Preserve]
        internal static void RegisterGeneratedFormatters()
        {
""");
        foreach (var fullTypeName in typeInitializers)
        {
            stringBuilder.AppendLine($"            {fullTypeName}.__RegisterMRubyValueFormatter();");
        }
        foreach (var statement in meta.RootStatements)
        {
            stringBuilder.AppendLine($"            {statement}");
        }
        stringBuilder.AppendLine("""
        }
    }
}
""");
        context.AddSource("ChibiRubySerializerModuleInitializer.g.cs", stringBuilder.ToString());
    }

    static void Emit(MRubyObjectModel model, StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine($$"""
// <auto-generated />
#nullable enable
#pragma warning disable CS0162 // Unreachable code
#pragma warning disable CS0219 // Variable assigned but never used
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602 // Possible null return
#pragma warning disable CS8604 // Possible null reference argument for parameter
#pragma warning disable CS8619 // Possible null reference assignment fix
#pragma warning disable CS8631 // The type cannot be used as type parameter in the generic type or method

using System;
using ChibiRuby;
using ChibiRuby.Serializer;
""");

        if (model.Namespace is { } ns)
        {
            stringBuilder.AppendLine($$"""
namespace {{ns}}
{
""");
        }

        stringBuilder.AppendLine($$"""
partial {{model.TypeDeclarationKeyword}} {{model.TypeName}}
{
""");
        EmitRegisterMethod(model, stringBuilder);
        EmitFormatter(model, stringBuilder);

        stringBuilder.AppendLine("}");
        if (model.Namespace is not null)
        {
            stringBuilder.AppendLine("}");
        }

        stringBuilder.AppendLine($$"""
#pragma warning restore CS0162 // Unreachable code
#pragma warning restore CS0219 // Variable assigned but never used
#pragma warning restore CS8600 // Converting null literal or possible null value to non-nullable type.
#pragma warning restore CS8601 // Possible null reference assignment
#pragma warning restore CS8602 // Possible null return
#pragma warning restore CS8604 // Possible null reference argument for parameter
#pragma warning restore CS8631 // The type cannot be used as type parameter in the generic type or method
""");
    }

    static void EmitRegisterMethod(MRubyObjectModel model, StringBuilder stringBuilder)
    {
        stringBuilder.AppendLine($$"""
    static bool __mrubyValueFormatterRegistered;

    [global::ChibiRuby.Serializer.Preserve]
    public static void __RegisterMRubyValueFormatter()
    {
        if (__mrubyValueFormatterRegistered) return;
        __mrubyValueFormatterRegistered = true;

        global::ChibiRuby.Serializer.GeneratedResolver.Register(new {{model.TypeName}}GeneratedFormatter());
""");
        foreach (var statement in model.EagerRegistrations)
        {
            stringBuilder.AppendLine($"        {statement}");
        }
        stringBuilder.AppendLine("""
    }

""");
    }

    static void EmitFormatter(MRubyObjectModel model, StringBuilder stringBuilder)
    {
        var returnType = model.IsValueType
            ? model.FullTypeName
            : $"{model.FullTypeName}?";

        stringBuilder.AppendLine($$"""
    [global::ChibiRuby.Serializer.Preserve]
    public class {{model.TypeName}}GeneratedFormatter : IMRubyValueFormatter<{{returnType}}>
    {
""");
        // Default
        foreach (var member in model.Members)
        {
            stringBuilder.Append($$"""
        static readonly byte[] {{member.Name}}KeyUtf8 =
""");
            stringBuilder.AppendByteArrayString(System.Text.Encoding.UTF8.GetBytes(member.KeyName));
            stringBuilder.AppendLine($"; // {member.KeyName}");
        }

        stringBuilder.AppendLine();

        EmitSerializeMethod(model, stringBuilder);
        EmitDeserializeMethod(model, stringBuilder);

        stringBuilder.AppendLine($$"""
    }
""");
    }

    static void EmitSerializeMethod(MRubyObjectModel model, StringBuilder stringBuilder)
    {
        var inputType = model.IsValueType
            ? model.FullTypeName
            : $"{model.FullTypeName}?";

        stringBuilder.AppendLine($$"""
        [global::ChibiRuby.Serializer.Preserve]
        public MRubyValue Serialize({{inputType}} value, MRubyState state, MRubyValueSerializerOptions options)
        {
""");
        if (!model.IsValueType)
        {
            stringBuilder.AppendLine($$"""
            if (value is null) return default;
""");
        }
        stringBuilder.AppendLine($$"""
            var props = state.NewHash({{model.Members.Count}});
""");

        foreach (var member in model.Members)
        {
            stringBuilder.AppendLine($$"""

            var key{{member.Name}} = new MRubyValue(state.Intern({{member.Name}}KeyUtf8));
            var value{{member.Name}} = options.Resolver.GetFormatterWithVerify<{{member.FullTypeName}}>()
                .Serialize(value.{{member.Name}}, state, options);
            props.Add(key{{member.Name}}, value{{member.Name}});
""");
        }

        stringBuilder.AppendLine($$"""

            return new MRubyValue(props);
        }

""");
    }

    static void EmitDeserializeMethod(MRubyObjectModel model, StringBuilder stringBuilder)
    {
        var returnType = model.IsValueType
            ? model.FullTypeName
            : $"{model.FullTypeName}?";
        stringBuilder.AppendLine($$"""
        [global::ChibiRuby.Serializer.Preserve]
        public {{returnType}} Deserialize(MRubyValue value, MRubyState state, MRubyValueSerializerOptions options)
        {
""");
        if (!model.IsValueType)
        {
            stringBuilder.AppendLine($$"""
            if (value.IsNil) return default;

""");
        }

        if (model.Members.Count <= 0)
        {
            stringBuilder.AppendLine($$"""
            return new {{model.TypeName}}();
        }

""");
            return;
        }

        stringBuilder.AppendLine($$"""
            MRubySerializationException.ThrowIfTypeMismatch(value, MRubyVType.Hash, "{{model.TypeName}}");
""");
        foreach (var member in model.Members)
        {
            stringBuilder.AppendLine($$"""
            var __{{member.Name}}__ = {{member.DefaultValueExpr}};
            var __{{member.Name}}NameSymbol__ = state.Intern({{member.Name}}KeyUtf8);
""");
        }

        stringBuilder.AppendLine($$"""
            var props = value.As<RHash>();
            foreach (var entry in props)
            {
""");
        var branching = "if";
        foreach (var member in model.Members)
        {
            stringBuilder.AppendLine($$"""
                {{branching}} (entry.Key.SymbolValue == __{{member.Name}}NameSymbol__)
                {
                    __{{member.Name}}__ = options.Resolver
                        .GetFormatterWithVerify<{{member.FullTypeName}}>()
                        .Deserialize(entry.Value, state, options);
                    continue;
                }
""");
            branching = "else if";
        }
        stringBuilder.AppendLine($$"""
            }
""");

        stringBuilder.Append($$"""
            return new {{model.TypeName}}
""");
        if (model.HasSelectedConstructor)
        {
            var parameters = string.Join(",", model.ConstructorParameterNames.Select(x => $"__{x}__"));
            stringBuilder.AppendLine($"({parameters})");
        }
        else
        {
            stringBuilder.AppendLine("()");
        }

        var setterMembers = model.Members.Where(x => !x.IsConstructorParameter).ToArray();
        if (setterMembers.Length > 0)
        {
            stringBuilder.AppendLine($$"""
            {
""");
            foreach (var setterMember in setterMembers)
            {
                stringBuilder.AppendLine($$"""
                {{setterMember.Name}} = __{{setterMember.Name}}__,
""");
            }
            stringBuilder.AppendLine($$"""
            }
""");
        }
        stringBuilder.AppendLine($$"""
            ;
        }
""");
    }
}
