// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace ChibiRuby.Debugger.Dap.Protocol;

static partial class ConfigurationDoneArgumentsFormatter
{
    
    public static ConfigurationDoneArguments Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static ConfigurationDoneArguments ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
            tokenizer.SkipValue();
        }
        return new ConfigurationDoneArguments();
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in ConfigurationDoneArguments value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in ConfigurationDoneArguments value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        w.WriteEndObject();
    }
}
