// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace ChibiRuby.Debugger.Dap.Protocol;

static partial class DisconnectArgumentsFormatter
{
    static global::System.ReadOnlySpan<byte> Name_Restart => "\"restart\":"u8;
    static global::System.ReadOnlySpan<byte> Name_TerminateDebuggee => "\"terminateDebuggee\":"u8;
    static global::System.ReadOnlySpan<byte> Name_SuspendDebuggee => "\"suspendDebuggee\":"u8;
    
    public static DisconnectArguments Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static DisconnectArguments ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        bool? __v_Restart = default;
        bool? __v_TerminateDebuggee = default;
        bool? __v_SuspendDebuggee = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 7:
                    if (__name.SequenceEqual("restart"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            __v_Restart = default;
                        }
                        else
                        
                        {
                            __v_Restart = tokenizer.ReadBoolean();
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                case 15:
                    if (__name.SequenceEqual("suspendDebuggee"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            __v_SuspendDebuggee = default;
                        }
                        else
                        
                        {
                            __v_SuspendDebuggee = tokenizer.ReadBoolean();
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                case 17:
                    if (__name.SequenceEqual("terminateDebuggee"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            __v_TerminateDebuggee = default;
                        }
                        else
                        
                        {
                            __v_TerminateDebuggee = tokenizer.ReadBoolean();
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new DisconnectArguments(Restart: __v_Restart, TerminateDebuggee: __v_TerminateDebuggee, SuspendDebuggee: __v_SuspendDebuggee);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in DisconnectArguments value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in DisconnectArguments value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        if (value.Restart is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_Restart);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_Restart);
            w.WriteBoolean(value.Restart.Value);
        }
        if (value.TerminateDebuggee is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_TerminateDebuggee);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_TerminateDebuggee);
            w.WriteBoolean(value.TerminateDebuggee.Value);
        }
        if (value.SuspendDebuggee is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_SuspendDebuggee);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_SuspendDebuggee);
            w.WriteBoolean(value.SuspendDebuggee.Value);
        }
        w.WriteEndObject();
    }
}
