// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace ChibiRuby.Debugger.Dap.Protocol;

static partial class ErrorResponseBodyFormatter
{
    static global::System.ReadOnlySpan<byte> Name_Error => "\"error\":"u8;
    
    public static ErrorResponseBody Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static ErrorResponseBody ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        Message? __v_Error = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 5:
                    if (__name.SequenceEqual("error"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            __v_Error = default;
                        }
                        else
                        
                        {
                            tokenizer.ReadStartObject();
                            var sub_Error = new Message();
                            MessageFormatter.ReadInto(ref tokenizer, sub_Error, options);
                            __v_Error = sub_Error;
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new ErrorResponseBody(Error: __v_Error);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in ErrorResponseBody value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in ErrorResponseBody value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        if (value.Error is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_Error);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_Error);
            MessageFormatter.WriteValue(ref w, value.Error!, options);
        }
        w.WriteEndObject();
    }
}
