// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace ChibiRuby.Debugger.Dap.Protocol;

static partial class RequestFormatter
{
    static global::System.ReadOnlySpan<byte> DiscriminatorName => "command"u8;
    
    public static Request Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        if (!tokenizer.TryPeekDiscriminator(DiscriminatorName, out var __disc)) tokenizer.ThrowFormatException("Missing discriminator 'command' on Request");
        if (__disc.SequenceEqual("attach"u8))
        {
            var v = new AttachRequest();
            AttachRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("configurationDone"u8))
        {
            var v = new ConfigurationDoneRequest();
            ConfigurationDoneRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("continue"u8))
        {
            var v = new ContinueRequest();
            ContinueRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("disconnect"u8))
        {
            var v = new DisconnectRequest();
            DisconnectRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("evaluate"u8))
        {
            var v = new EvaluateRequest();
            EvaluateRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("initialize"u8))
        {
            var v = new InitializeRequest();
            InitializeRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("launch"u8))
        {
            var v = new LaunchRequest();
            LaunchRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("next"u8))
        {
            var v = new NextRequest();
            NextRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("pause"u8))
        {
            var v = new PauseRequest();
            PauseRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("scopes"u8))
        {
            var v = new ScopesRequest();
            ScopesRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("setBreakpoints"u8))
        {
            var v = new SetBreakpointsRequest();
            SetBreakpointsRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("stackTrace"u8))
        {
            var v = new StackTraceRequest();
            StackTraceRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("stepIn"u8))
        {
            var v = new StepInRequest();
            StepInRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("stepOut"u8))
        {
            var v = new StepOutRequest();
            StepOutRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("terminate"u8))
        {
            var v = new TerminateRequest();
            TerminateRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("threads"u8))
        {
            var v = new ThreadsRequest();
            ThreadsRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        if (__disc.SequenceEqual("variables"u8))
        {
            var v = new VariablesRequest();
            VariablesRequestFormatter.ReadInto(ref tokenizer, v, options);
            return v;
        }
        tokenizer.ThrowFormatException("Unknown discriminator value '" + global::System.Text.Encoding.UTF8.GetString(__disc) + "' on Request");
        return default!; // unreachable
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in Request value, NoJsonSerializerOptions options)
    {
        if (value is AttachRequest __sub_AttachRequest)
        {
            AttachRequestFormatter.Serialize(writer, __sub_AttachRequest, options);
            return;
        }
        if (value is ConfigurationDoneRequest __sub_ConfigurationDoneRequest)
        {
            ConfigurationDoneRequestFormatter.Serialize(writer, __sub_ConfigurationDoneRequest, options);
            return;
        }
        if (value is ContinueRequest __sub_ContinueRequest)
        {
            ContinueRequestFormatter.Serialize(writer, __sub_ContinueRequest, options);
            return;
        }
        if (value is DisconnectRequest __sub_DisconnectRequest)
        {
            DisconnectRequestFormatter.Serialize(writer, __sub_DisconnectRequest, options);
            return;
        }
        if (value is EvaluateRequest __sub_EvaluateRequest)
        {
            EvaluateRequestFormatter.Serialize(writer, __sub_EvaluateRequest, options);
            return;
        }
        if (value is InitializeRequest __sub_InitializeRequest)
        {
            InitializeRequestFormatter.Serialize(writer, __sub_InitializeRequest, options);
            return;
        }
        if (value is LaunchRequest __sub_LaunchRequest)
        {
            LaunchRequestFormatter.Serialize(writer, __sub_LaunchRequest, options);
            return;
        }
        if (value is NextRequest __sub_NextRequest)
        {
            NextRequestFormatter.Serialize(writer, __sub_NextRequest, options);
            return;
        }
        if (value is PauseRequest __sub_PauseRequest)
        {
            PauseRequestFormatter.Serialize(writer, __sub_PauseRequest, options);
            return;
        }
        if (value is ScopesRequest __sub_ScopesRequest)
        {
            ScopesRequestFormatter.Serialize(writer, __sub_ScopesRequest, options);
            return;
        }
        if (value is SetBreakpointsRequest __sub_SetBreakpointsRequest)
        {
            SetBreakpointsRequestFormatter.Serialize(writer, __sub_SetBreakpointsRequest, options);
            return;
        }
        if (value is StackTraceRequest __sub_StackTraceRequest)
        {
            StackTraceRequestFormatter.Serialize(writer, __sub_StackTraceRequest, options);
            return;
        }
        if (value is StepInRequest __sub_StepInRequest)
        {
            StepInRequestFormatter.Serialize(writer, __sub_StepInRequest, options);
            return;
        }
        if (value is StepOutRequest __sub_StepOutRequest)
        {
            StepOutRequestFormatter.Serialize(writer, __sub_StepOutRequest, options);
            return;
        }
        if (value is TerminateRequest __sub_TerminateRequest)
        {
            TerminateRequestFormatter.Serialize(writer, __sub_TerminateRequest, options);
            return;
        }
        if (value is ThreadsRequest __sub_ThreadsRequest)
        {
            ThreadsRequestFormatter.Serialize(writer, __sub_ThreadsRequest, options);
            return;
        }
        if (value is VariablesRequest __sub_VariablesRequest)
        {
            VariablesRequestFormatter.Serialize(writer, __sub_VariablesRequest, options);
            return;
        }
        throw new global::System.InvalidOperationException("Unknown Request subtype: " + value!.GetType());
    }
}
