// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace ChibiRuby.Debugger.Dap.Protocol;

static partial class ScopesArgumentsFormatter
{
    static global::System.ReadOnlySpan<byte> Name_FrameId => "\"frameId\":"u8;
    
    public static ScopesArguments Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static ScopesArguments ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        int __v_FrameId = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 7:
                    if (__name.SequenceEqual("frameId"u8))
                    
                    {
                        __v_FrameId = tokenizer.ReadInt32();
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new ScopesArguments(FrameId: __v_FrameId);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in ScopesArguments value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in ScopesArguments value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        w.WritePropertyNameRaw(Name_FrameId);
        w.WriteInt32(value.FrameId);
        w.WriteEndObject();
    }
}
