// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace ChibiRuby.Debugger.Dap.Protocol;

static partial class StackTraceResponseBodyFormatter
{
    static global::System.ReadOnlySpan<byte> Name_StackFrames => "\"stackFrames\":"u8;
    static global::System.ReadOnlySpan<byte> Name_TotalFrames => "\"totalFrames\":"u8;
    
    public static StackTraceResponseBody Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static StackTraceResponseBody ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        StackFrame[] __v_StackFrames = default;
        uint? __v_TotalFrames = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 11:
                    if (__name.SequenceEqual("stackFrames"u8))
                    
                    {
                        tokenizer.ReadStartArray();
                        var buf_StackFrames = global::System.Array.Empty<StackFrame>();
                        var count_StackFrames = 0;
                        while (!tokenizer.TryReadEndArray())
                        {
                            if (count_StackFrames == buf_StackFrames.Length) global::System.Array.Resize(ref buf_StackFrames, buf_StackFrames.Length == 0 ? 4 : buf_StackFrames.Length * 2);
                            tokenizer.ReadStartObject();
                            var elem = new StackFrame();
                            StackFrameFormatter.ReadInto(ref tokenizer, elem, options);
                            buf_StackFrames[count_StackFrames++] = elem;
                        }
                        if (count_StackFrames != buf_StackFrames.Length) global::System.Array.Resize(ref buf_StackFrames, count_StackFrames);
                        __v_StackFrames = buf_StackFrames;
                    }
                    else if (__name.SequenceEqual("totalFrames"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            __v_TotalFrames = default;
                        }
                        else
                        
                        {
                            __v_TotalFrames = tokenizer.ReadUInt32();
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new StackTraceResponseBody(StackFrames: __v_StackFrames, TotalFrames: __v_TotalFrames);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in StackTraceResponseBody value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in StackTraceResponseBody value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        w.WritePropertyNameRaw(Name_StackFrames);
        w.WriteStartArray();
        foreach (var item in value.StackFrames!)
        {
            StackFrameFormatter.WriteValue(ref w, item, options);
        }
        w.WriteEndArray();
        if (value.TotalFrames is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_TotalFrames);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_TotalFrames);
            w.WriteUInt32(value.TotalFrames.Value);
        }
        w.WriteEndObject();
    }
}
