// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace MRubyCS.Debugger.Dap.Protocol;

static partial class AttachRequestArgumentsFormatter
{
    static global::System.ReadOnlySpan<byte> Name_Restart => "\"__restart\":"u8;
    static global::System.ReadOnlySpan<byte> Name_Program => "\"program\":"u8;
    
    public static AttachRequestArguments Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        var value = new AttachRequestArguments();
        ReadInto(ref tokenizer, value, options);
        return value;
    }
    
    internal static void ReadInto(ref Utf8JsonTokenizer tokenizer, AttachRequestArguments value, NoJsonSerializerOptions options)
    {
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 7:
                    if (__name.SequenceEqual("program"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            value.Program = default;
                        }
                        else
                        
                        {
                            value.Program = tokenizer.ReadString();
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                case 9:
                    if (__name.SequenceEqual("__restart"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            value.Restart = default;
                        }
                        else
                        
                        {
                            tokenizer.SkipValue();
                            value.Restart = null;
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in AttachRequestArguments value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, AttachRequestArguments value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        if (value.Restart is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_Restart);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_Restart);
            w.WriteNull(); // any-typed value not yet supported
        }
        if (value.Program is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_Program);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_Program);
            w.WriteString(value.Program);
        }
        w.WriteEndObject();
    }
}
