// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace MRubyCS.Debugger.Dap.Protocol;

static partial class ChecksumFormatter
{
    static global::System.ReadOnlySpan<byte> Name_Algorithm => "\"algorithm\":"u8;
    static global::System.ReadOnlySpan<byte> Name_ChecksumValue => "\"checksum\":"u8;
    
    public static Checksum Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static Checksum ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        ChecksumAlgorithm __v_Algorithm = default;
        string __v_ChecksumValue = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 8:
                    if (__name.SequenceEqual("checksum"u8))
                    
                    {
                        __v_ChecksumValue = tokenizer.ReadString();
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                case 9:
                    if (__name.SequenceEqual("algorithm"u8))
                    
                    {
                        __v_Algorithm = ChecksumAlgorithmFormatter.ReadValue(ref tokenizer);
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new Checksum(Algorithm: __v_Algorithm, ChecksumValue: __v_ChecksumValue);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in Checksum value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in Checksum value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        w.WritePropertyNameRaw(Name_Algorithm);
        ChecksumAlgorithmFormatter.WriteValue(ref w, value.Algorithm);
        w.WritePropertyNameRaw(Name_ChecksumValue);
        w.WriteString(value.ChecksumValue);
        w.WriteEndObject();
    }
}
