// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace MRubyCS.Debugger.Dap.Protocol;

static partial class ContinuedEventBodyFormatter
{
    static global::System.ReadOnlySpan<byte> Name_ThreadId => "\"threadId\":"u8;
    static global::System.ReadOnlySpan<byte> Name_AllThreadsContinued => "\"allThreadsContinued\":"u8;
    
    public static ContinuedEventBody Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static ContinuedEventBody ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        int __v_ThreadId = default;
        bool? __v_AllThreadsContinued = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 8:
                    if (__name.SequenceEqual("threadId"u8))
                    
                    {
                        __v_ThreadId = tokenizer.ReadInt32();
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                case 19:
                    if (__name.SequenceEqual("allThreadsContinued"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            __v_AllThreadsContinued = default;
                        }
                        else
                        
                        {
                            __v_AllThreadsContinued = tokenizer.ReadBoolean();
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new ContinuedEventBody(ThreadId: __v_ThreadId, AllThreadsContinued: __v_AllThreadsContinued);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in ContinuedEventBody value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in ContinuedEventBody value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        w.WritePropertyNameRaw(Name_ThreadId);
        w.WriteInt32(value.ThreadId);
        if (value.AllThreadsContinued is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_AllThreadsContinued);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_AllThreadsContinued);
            w.WriteBoolean(value.AllThreadsContinued.Value);
        }
        w.WriteEndObject();
    }
}
