// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace MRubyCS.Debugger.Dap.Protocol;

static partial class ScopesResponseBodyFormatter
{
    static global::System.ReadOnlySpan<byte> Name_Scopes => "\"scopes\":"u8;
    
    public static ScopesResponseBody Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static ScopesResponseBody ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        Scope[] __v_Scopes = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 6:
                    if (__name.SequenceEqual("scopes"u8))
                    
                    {
                        tokenizer.ReadStartArray();
                        var list_Scopes = new global::System.Collections.Generic.List<Scope>();
                        while (!tokenizer.TryReadEndArray())
                        {
                            tokenizer.ReadStartObject();
                            var elem = new Scope();
                            ScopeFormatter.ReadInto(ref tokenizer, elem, options);
                            list_Scopes.Add(elem);
                        }
                        __v_Scopes = list_Scopes.ToArray();
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new ScopesResponseBody(Scopes: __v_Scopes);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in ScopesResponseBody value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in ScopesResponseBody value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        w.WritePropertyNameRaw(Name_Scopes);
        w.WriteStartArray();
        foreach (var item in value.Scopes!)
        {
            ScopeFormatter.WriteValue(ref w, item, options);
        }
        w.WriteEndArray();
        w.WriteEndObject();
    }
}
