// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace MRubyCS.Debugger.Dap.Protocol;

static partial class TerminatedEventBodyFormatter
{
    static global::System.ReadOnlySpan<byte> Name_Restart => "\"restart\":"u8;
    
    public static TerminatedEventBody Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static TerminatedEventBody ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        object? __v_Restart = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 7:
                    if (__name.SequenceEqual("restart"u8))
                    
                    {
                        if (tokenizer.TryReadNull())
                        {
                            __v_Restart = default;
                        }
                        else
                        
                        {
                            tokenizer.SkipValue();
                            __v_Restart = null;
                        }
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new TerminatedEventBody(Restart: __v_Restart);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in TerminatedEventBody value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in TerminatedEventBody value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        if (value.Restart is null)
        {
            if (!options.SkipNullProperties)
            
            {
                w.WritePropertyNameRaw(Name_Restart);
                w.WriteNull();
            }
        }
        else
        
        {
            w.WritePropertyNameRaw(Name_Restart);
            w.WriteNull(); // any-typed value not yet supported
        }
        w.WriteEndObject();
    }
}
