// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace MRubyCS.Debugger.Dap.Protocol;

static partial class ThreadFormatter
{
    static global::System.ReadOnlySpan<byte> Name_Id => "\"id\":"u8;
    static global::System.ReadOnlySpan<byte> Name_Name => "\"name\":"u8;
    
    public static Thread Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static Thread ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        int __v_Id = default;
        string __v_Name = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 2:
                    if (__name.SequenceEqual("id"u8))
                    
                    {
                        __v_Id = tokenizer.ReadInt32();
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                case 4:
                    if (__name.SequenceEqual("name"u8))
                    
                    {
                        __v_Name = tokenizer.ReadString();
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new Thread(Id: __v_Id, Name: __v_Name);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in Thread value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in Thread value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        w.WritePropertyNameRaw(Name_Id);
        w.WriteInt32(value.Id);
        w.WritePropertyNameRaw(Name_Name);
        w.WriteString(value.Name);
        w.WriteEndObject();
    }
}
