// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.Buffers;

namespace MRubyCS.Debugger.Dap.Protocol;

static partial class ThreadsResponseBodyFormatter
{
    static global::System.ReadOnlySpan<byte> Name_Threads => "\"threads\":"u8;
    
    public static ThreadsResponseBody Deserialize(global::System.ReadOnlySpan<byte> utf8Json, NoJsonSerializerOptions options)
    {
        var tokenizer = new Utf8JsonTokenizer(utf8Json);
        tokenizer.ReadStartObject();
        return ReadValue(ref tokenizer, options);
    }
    
    internal static ThreadsResponseBody ReadValue(ref Utf8JsonTokenizer tokenizer, NoJsonSerializerOptions options)
    {
        Thread[] __v_Threads = default;
        while (tokenizer.TryReadPropertyName(out var __name))
        {
            switch (__name.Length)
            {
                case 7:
                    if (__name.SequenceEqual("threads"u8))
                    
                    {
                        tokenizer.ReadStartArray();
                        var list_Threads = new global::System.Collections.Generic.List<Thread>();
                        while (!tokenizer.TryReadEndArray())
                        {
                            tokenizer.ReadStartObject();
                            list_Threads.Add(ThreadFormatter.ReadValue(ref tokenizer, options));
                        }
                        __v_Threads = list_Threads.ToArray();
                    }
                    else
                    
                    {
                        if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                        tokenizer.SkipValue();
                    }
                    break;
                default:
                    if (options.StrictExtraProperties) tokenizer.ThrowFormatException("Unknown property '" + global::System.Text.Encoding.UTF8.GetString(__name) + "'");
                    tokenizer.SkipValue();
                    break;
            }
        }
        return new ThreadsResponseBody(Threads: __v_Threads);
    }
    
    public static void Serialize(global::System.Buffers.IBufferWriter<byte> writer, in ThreadsResponseBody value, NoJsonSerializerOptions options)
    {
        var w = new Utf8JsonBufferWriter(writer);
        WriteValue(ref w, in value, options);
        w.Flush();
    }
    
    internal static void WriteValue(ref Utf8JsonBufferWriter w, in ThreadsResponseBody value, NoJsonSerializerOptions options)
    {
        w.WriteStartObject();
        w.WritePropertyNameRaw(Name_Threads);
        w.WriteStartArray();
        foreach (var item in value.Threads!)
        {
            ThreadFormatter.WriteValue(ref w, in item, options);
        }
        w.WriteEndArray();
        w.WriteEndObject();
    }
}
