// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <summary>
/// The checksum of an item calculated by the specified algorithm.
/// </summary>
/// <param name="Algorithm">The algorithm used to calculate this checksum.</param>
/// <param name="ChecksumValue">Value of the checksum, encoded as a hexadecimal value.</param>
public readonly partial record struct Checksum(ChecksumAlgorithm Algorithm, string ChecksumValue);
