// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class ConfigurationDoneRequest : Request
{
    public new ConfigurationDoneArguments? Arguments { get; set; }
}
