// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <param name="AllThreadsContinued">If omitted or set to `true`, this response signals to the client that all threads have been resumed. The value `false` indicates that not all threads were resumed.</param>
public readonly partial record struct ContinueResponseBody(bool? AllThreadsContinued = default);
