// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class ContinuedEvent : Event
{
    public new ContinuedEventBody Body { get; set; }
}
