// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class ContinueRequest : Request
{
    public new ContinueArguments Arguments { get; set; }
}
