// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <summary>
/// Arguments for `disconnect` request.
/// </summary>
/// <param name="Restart">A value of true indicates that this `disconnect` request is part of a restart sequence.</param>
/// <param name="TerminateDebuggee">Indicates whether the debuggee should be terminated when the debugger is disconnected.</param>
/// <param name="TerminateDebuggee">If unspecified, the debug adapter is free to do whatever it thinks is best.</param>
/// <param name="TerminateDebuggee">The attribute is only honored by a debug adapter if the corresponding capability `supportTerminateDebuggee` is true.</param>
/// <param name="SuspendDebuggee">Indicates whether the debuggee should stay suspended when the debugger is disconnected.</param>
/// <param name="SuspendDebuggee">If unspecified, the debuggee should resume execution.</param>
/// <param name="SuspendDebuggee">The attribute is only honored by a debug adapter if the corresponding capability `supportSuspendDebuggee` is true.</param>
public readonly partial record struct DisconnectArguments(bool? Restart = default, bool? TerminateDebuggee = default, bool? SuspendDebuggee = default);
