// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class DisconnectRequest : Request
{
    public new DisconnectArguments? Arguments { get; set; }
}
