// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class ErrorResponse : Response
{
    public new ErrorResponseBody Body { get; set; }
}
