// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class EvaluateRequest : Request
{
    public new EvaluateArguments Arguments { get; set; } = null!;
}
