// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class InitializeRequest : Request
{
    public new InitializeRequestArguments Arguments { get; set; } = null!;
}
