// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <summary>
/// Arguments for `next` request.
/// </summary>
/// <param name="ThreadId">Specifies the thread for which to resume execution for one step (of the given granularity).</param>
/// <param name="SingleThread">If this flag is true, all other suspended threads are not resumed.</param>
/// <param name="Granularity">Stepping granularity. If no granularity is specified, a granularity of `statement` is assumed.</param>
public readonly partial record struct NextArguments(int ThreadId, bool? SingleThread = default, SteppingGranularity? Granularity = null);
