// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class OutputEvent : Event
{
    public new OutputEventBody Body { get; set; } = null!;
}
