// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <summary>
/// Arguments for `pause` request.
/// </summary>
/// <param name="ThreadId">Pause execution for this thread.</param>
public readonly partial record struct PauseArguments(int ThreadId);
