// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public abstract partial class Request : ProtocolMessage
{
    /// <summary>
    /// The command to execute.
    /// </summary>
    public string Command { get; set; } = null!;
    
    /// <summary>
    /// Object containing arguments for the command.
    /// </summary>
    public object? Arguments { get; set; }
}
