// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <summary>
/// Arguments for `scopes` request.
/// </summary>
/// <param name="FrameId">Retrieve the scopes for the stack frame identified by `frameId`. The `frameId` must have been obtained in the current suspended state. See &#39;Lifetime of Object References&#39; in the Overview section for details.</param>
public readonly partial record struct ScopesArguments(int FrameId);
