// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class ScopesResponse : Response
{
    public new ScopesResponseBody Body { get; set; }
}
