// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <param name="Scopes">The scopes of the stack frame. If the array has length zero, there are no scopes available.</param>
public readonly partial record struct ScopesResponseBody(Scope[] Scopes);
