// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class SetBreakpointsResponse : Response
{
    public new SetBreakpointsResponseBody Body { get; set; }
}
