// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <param name="StackFrames">The frames of the stack frame. If the array has length zero, there are no stack frames available.</param>
/// <param name="StackFrames">This means that there is no location information available.</param>
/// <param name="TotalFrames">The total number of frames available in the stack. If omitted or if `totalFrames` is larger than the available frames, a client is expected to request frames until a request returns less frames than requested (which indicates the end of the stack). Returning monotonically increasing `totalFrames` values for subsequent requests can be used to enforce paging in the client.</param>
public readonly partial record struct StackTraceResponseBody(StackFrame[] StackFrames, uint? TotalFrames = default);
