// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class StepInRequest : Request
{
    public new StepInArguments Arguments { get; set; } = null!;
}
