// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

/// <summary>
/// The granularity of one &#39;step&#39; in the stepping requests `next`, `stepIn`, `stepOut`, and `stepBack`.
/// </summary>
public enum SteppingGranularity
{
    Statement,
    Line,
    Instruction,
}
