// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class TerminatedEvent : Event
{
    public new TerminatedEventBody? Body { get; set; }
}
