// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class TerminateRequest : Request
{
    public new TerminateArguments? Arguments { get; set; }
}
