// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class ThreadsResponse : Response
{
    public new ThreadsResponseBody Body { get; set; }
}
