// <auto-generated/>
#nullable enable
#pragma warning disable

namespace MRubyCS.Debugger.Dap.Protocol;

public partial class VariablesRequest : Request
{
    public new VariablesArguments Arguments { get; set; } = null!;
}
