// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// Arguments for `attach` request. Additional attributes are implementation specific.
/// </summary>
public partial class AttachRequestArguments
{
    /// <summary>
    /// Arbitrary data from the previous, restarted session.
    /// The data is sent as the `restart` attribute of the `terminated` event.
    /// The client should leave the data intact.
    /// </summary>
    public object? Restart { get; set; }
    
    /// <summary>
    /// ChibiRuby adapter-specific: absolute path to the Ruby script the host is running (used to resolve relative source paths in stack frames).
    /// </summary>
    public string? Program { get; set; }
}
