// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class AttachRequest : Request
{
    public new AttachRequestArguments Arguments { get; set; } = null!;
}
