// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// Names of checksum algorithms that may be supported by a debug adapter.
/// </summary>
public enum ChecksumAlgorithm
{
    MD5,
    SHA1,
    SHA256,
    Timestamp,
}
