// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// Datatype of values in this column. Defaults to `string` if not specified.
/// </summary>
public enum ColumnDescriptorType
{
    String,
    Number,
    Boolean,
    UnixTimestampUTC,
}
