// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// Arguments for `configurationDone` request.
/// </summary>
public readonly partial record struct ConfigurationDoneArguments();
