// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// Arguments for `continue` request.
/// </summary>
/// <param name="ThreadId">Specifies the active thread. If the debug adapter supports single thread execution (see `supportsSingleThreadExecutionRequests`) and the argument `singleThread` is true, only the thread with this ID is resumed.</param>
/// <param name="SingleThread">If this flag is true, execution is resumed only for the thread with given `threadId`.</param>
public readonly partial record struct ContinueArguments(int ThreadId, bool? SingleThread = default);
