// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class ContinueResponse : Response
{
    public new ContinueResponseBody Body { get; set; }
}
