// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <param name="Error">A structured error message.</param>
public readonly partial record struct ErrorResponseBody(Message? Error = null);
