// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class EvaluateResponse : Response
{
    public new EvaluateResponseBody Body { get; set; } = null!;
}
