// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class InitializeResponse : Response
{
    /// <summary>
    /// The capabilities of this debug adapter.
    /// </summary>
    public new Capabilities? Body { get; set; }
}
