// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class LaunchRequest : Request
{
    public new LaunchRequestArguments Arguments { get; set; } = null!;
}
