// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class NextRequest : Request
{
    public new NextArguments Arguments { get; set; }
}
