// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// Support for keeping an output log organized by grouping related messages.
/// </summary>
public enum OutputEventBodyGroup
{
    Start,
    StartCollapsed,
    End,
}
