// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class PauseRequest : Request
{
    public new PauseArguments Arguments { get; set; }
}
