// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class ScopesRequest : Request
{
    public new ScopesArguments Arguments { get; set; }
}
