// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class SetBreakpointsRequest : Request
{
    public new SetBreakpointsArguments Arguments { get; set; } = null!;
}
