// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <param name="Breakpoints">Information about the breakpoints.</param>
/// <param name="Breakpoints">The array elements are in the same order as the elements of the `breakpoints` (or the deprecated `lines`) array in the arguments.</param>
public readonly partial record struct SetBreakpointsResponseBody(Breakpoint[] Breakpoints);
