// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class StackTraceResponse : Response
{
    public new StackTraceResponseBody Body { get; set; }
}
