// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class StepOutRequest : Request
{
    public new StepOutArguments Arguments { get; set; }
}
