// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class StoppedEvent : Event
{
    public new StoppedEventBody Body { get; set; } = null!;
}
