// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// Arguments for `terminate` request.
/// </summary>
/// <param name="Restart">A value of true indicates that this `terminate` request is part of a restart sequence.</param>
public readonly partial record struct TerminateArguments(bool? Restart = default);
