// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <param name="Restart">A debug adapter may set `restart` to true (or to an arbitrary object) to request that the client restarts the session.</param>
/// <param name="Restart">The value is not interpreted by the client and passed unmodified as an attribute `__restart` to the `launch` and `attach` requests.</param>
public readonly partial record struct TerminatedEventBody(object? Restart = null);
