// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// A Thread
/// </summary>
/// <param name="Id">Unique identifier for the thread.</param>
/// <param name="Name">The name of the thread.</param>
public readonly partial record struct Thread(int Id, string Name);
