// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <param name="Threads">All threads.</param>
public readonly partial record struct ThreadsResponseBody(Thread[] Threads);
