// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <param name="Variables">All (or a range) of variables for the given variable reference.</param>
public readonly partial record struct VariablesResponseBody(Variable[] Variables);
