// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

/// <summary>
/// Filter to limit the child variables to either named or indexed. If omitted, both types are fetched.
/// </summary>
public enum VariablesArgumentsFilter
{
    Indexed,
    Named,
}
