// <auto-generated/>
#nullable enable
#pragma warning disable

namespace ChibiRuby.Debugger.Dap.Protocol;

public partial class VariablesResponse : Response
{
    public new VariablesResponseBody Body { get; set; }
}
