name: Build mruby-compiler native

on:
  workflow_dispatch: {}

jobs:
  build-windows:
    uses: ./.github/workflows/build-mruby-compiler.windows.yaml
  build-linux:
    uses: ./.github/workflows/build-mruby-compiler.linux.yaml
  build-macOS:
    uses: ./.github/workflows/build-mruby-compiler.macOS.yaml
  build-android:
    uses: ./.github/workflows/build-mruby-compiler.android.yaml
  build-iOS:
    uses: ./.github/workflows/build-mruby-compiler.ios.yaml
  build-wasm:
    uses: ./.github/workflows/build-mruby-compiler.wasm.yaml
